### PR TITLE
Add Signal logging

### LINKED ISSUE #619: No value type logger defined for value type 'SIGNAL'
## Description

A new record value type has been introduced to Zeebe SNAPSHOT. This was detected by the [Run Tests against Zeebe SNAPSHOT version](https://github.com/camunda/zeebe-process-test/actions/runs/3778724874/jobs/6423429157) workflow.

```

Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.028 s <<< FAILURE! - in io.camunda.zeebe.process.test.filters.logger.RecordStreamLoggerTest
Error:  io.camunda.zeebe.process.test.filters.logger.RecordStreamLoggerTest.testAllValueTypesAreMapped  Time elapsed: 0.003 s  <<< FAILURE!
org.assertj.core.error.AssertJMultipleFailuresError: 

Multiple Failures (1 failure)
-- failure 1 --No value type logger defined for value type 'SIGNAL'
at RecordStreamLoggerTest.lambda$testAllValueTypesAreMapped$0(RecordStreamLoggerTest.java:66)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at io.camunda.zeebe.process.test.filters.logger.RecordStreamLoggerTest.testAllValueTypesAreMapped(RecordStreamLoggerTest.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  io.camunda.zeebe.process.test.filters.logger.RecordStreamLoggerTest.testAllValueTypesAreMapped
Error:    Run 1: RecordStreamLoggerTest.testAllValueTypesAreMapped:68 
Multiple Failures (1 failure)
-- failure 1 --No value type logger defined for value type 'SIGNAL'
at RecordStreamLoggerTest.lambda$testAllValueTypesAreMapped$0(RecordStreamLoggerTest.java:66)
Error:    Run 2: RecordStreamLoggerTest.testAllValueTypesAreMapped:68 
Multiple Failures (1 failure)
-- failure 1 --No value type logger defined for value type 'SIGNAL'
at RecordStreamLoggerTest.lambda$testAllValueTypesAreMapped$0(RecordStreamLoggerTest.java:66)
Error:    Run 3: RecordStreamLoggerTest.testAllValueTypesAreMapped:68 
Multiple Failures (1 failure)
-- failure 1 --No value type logger defined for value type 'SIGNAL'
at RecordStreamLoggerTest.lambda$testAllValueTypesAreMapped$0(RecordStreamLoggerTest.java:66)
Error:    Run 4: RecordStreamLoggerTest.testAllValueTypesAreMapped:68 
Multiple Failures (1 failure)
-- failure 1 --No value type logger defined for value type 'SIGNAL'
at RecordStreamLoggerTest.lambda$testAllValueTypesAreMapped$0(RecordStreamLoggerTest.java:66)
Error:    Run 5: RecordStreamLoggerTest.testAllValueTypesAreMapped:68 
Multiple Failures (1 failure)
-- failure 1 --No value type logger defined for value type 'SIGNAL'
at RecordStreamLoggerTest.lambda$testAllValueTypesAreMapped$0(RecordStreamLoggerTest.java:66)
Error:    Run 6: RecordStreamLoggerTest.testAllValueTypesAreMapped:68 
Multiple Failures (1 failure)
-- failure 1 --No value type logger defined for value type 'SIGNAL'
at RecordStreamLoggerTest.lambda$testAllValueTypesAreMapped$0(RecordStreamLoggerTest.java:66)
[INFO] 
[INFO] 
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 0

```

### PR DESCRIPTION
**Pull request by Zelldon**
## Description

The current test against Zeebe snapshot fails, because we have no logging for signal event defined. This PR fixes this issue.

Failing build https://github.com/camunda/zeebe-process-test/actions/runs/3784816277/jobs/6434402216
Commit which adds logging https://github.com/camunda/zeebe-process-test/commit/f01b7b62b938c723bb00c5bbf50d0a4d3b1ef824

## Related issues

closes #619 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually

Documentation:
* [ ] Javadoc has been written
* [ ] The documentation is updated

### CODE REVIEW

**Review by koevskinikola — APPROVED** [review]
LGTM :rocket: 

There are failures due to the new `evaluateDecision` rpc method that I merged last week. I'm currently working on implementing it in the Java client. I think we can ignore those failures for this PR.

**Comment by Zelldon** [comment]
Thanks @koevskinikola :bow: I guess then we can't move to snapshot, otherwise the CI will also fail everytime I guess?

**Comment by koevskinikola** [comment]
@Zelldon yes, the Java client PR (https://github.com/camunda/zeebe/pull/11335) needs to be reviewed and merged first, to prevent the CI from failing on snapshot.

**Comment by Zelldon** [comment]
Ok if you are done you can assign me for review @koevskinikola

**Comment by skayliu** [comment]
Hi,@Zelldon, you can add the related issue #619, :smile:

**Comment by Zelldon** [comment]
Ah good catch have overseen it thanks @skayliu :bow:

**Review by remcowesterhoud — APPROVED** [review]
bors merge

**Pull request merged**
