### PR TITLE
[Backport stable/8.0] automerge camundait and backport PRs

### PR DESCRIPTION
**Pull request by remcowesterhoud**
Backport #840 to stable/8.0

### CODE REVIEW

**Review by korthout — APPROVED** [review]
LGTM 👍 

bors merge

**Comment by remcowesterhoud** [comment]
bors cancel

same error as the other backport

**Comment by remcowesterhoud** [comment]
bors retry

**Comment by remcowesterhoud** [comment]
bors cancel ?

**Comment by remcowesterhoud** [comment]
bors merge

**Pull request merged**
