### PR TITLE
Add USER and CLOCK ValueTypes to the RecordStreamLogger

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

These ValueTypes were missing causing failing tests on the main branch. I've added a quick summary of the records to the logger to fix this problem.

## Related issues

N/A

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually

Documentation:
* [ ] Javadoc has been written
* [ ] The documentation is updated

### CODE REVIEW

**Review by tmetzke — APPROVED** [review]
👍

**Comment by tmetzke** [comment]
Interesting CI failures 🤔 They can't be related to the changes here, as far as I can see.

**Comment by remcowesterhoud** [comment]
@tmetzke Just saw them as well. I'll still see if I can fix them in this PR 😄

**Comment by remcowesterhoud** [comment]
Nevermind, it becomes complex fast. I'll create an issue for it 😄

**Pull request merged**
