### PR TITLE
Properly support Signal broadcasting

### LINKED ISSUE #964: Support sending signals
**Description**

Signal events are introduced in camunda 8.3.0. When using the zeebe client to create a new signal event in a @ZeebeProcessTest the following error occurs:

```
io.camunda.zeebe.client.api.command.ClientStatusException
 at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException([ZeebeClientFutureImpl.java:116](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join([ZeebeClientFutureImpl.java:54](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
...
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN
 at java.base/java.util.concurrent.CompletableFuture.reportGet([CompletableFuture.java:396](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.base/java.util.concurrent.CompletableFuture.get([CompletableFuture.java:2073](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join([ZeebeClientFutureImpl.java:52](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 ... 72 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
 at io.grpc.Status.asRuntimeException([Status.java:537](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose([ClientCalls.java:481](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
...
```

This issue is for signal events to be supported in zeebe-process-test

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

I only implemented half of the Signal support 🙈 . This PR adds the remainder and adds a test to verify it's possible to broadcast signals.

## Related issues

closes #964

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to backport the fix

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually

Documentation:
* [ ] Javadoc has been written
* [ ] The documentation is updated

### CODE REVIEW

**Review by nicpuppa — APPROVED** [review]
Thanks @remcowesterhoud for this last 🍪

LGTM!

What is the other half 🤣 ?

**Comment by remcowesterhoud** [comment]
[This](https://github.com/camunda/zeebe-process-test/pull/680/files) was the other half 😄 

bors merge

**Comment by nicpuppa** [comment]
Please stop 🤣

**Comment by korthout** [comment]
It was running on it's own comments containing the magic word: `<slash>backport`

The workflow doesn't cancel this out. See Zeebe repo on how to do this: https://github.com/camunda/zeebe/blob/main/.github/workflows/backport.yml#L21

**Comment by remcowesterhoud** [comment]
Yeah I figured, I'll create a PR for that

**Comment by remcowesterhoud** [comment]
Url contains the magic word 😭

**Comment by korthout** [comment]
Disabled the workflow now

**Comment by korthout** [comment]
@remcowesterhoud Once fixed, we can re-enable the workflow here:
https://github.com/camunda/zeebe-process-test/actions/workflows/backport.yml

**Comment by remcowesterhoud** [comment]
🤞 

/backport

**Comment by remcowesterhoud** [comment]
So to keep things a bit clear

8.3 backport is merged already https://github.com/camunda/zeebe-process-test/pull/967
I will do 8.2 manually.

**Pull request merged**
