### PR TITLE
fix: build stream processor with SimpleMeterRegistry

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

Provide to stream processor a simple meter registry

### CODE REVIEW

**Review by mustafadagher — COMMENTED** [review]
The changes LGTM! But, let's check why the `TimerTest` is failing.

**Comment by nicpuppa** [comment]
> The changes LGTM! But, let's check why the `TimerTest` is failing.

I already raised this in [this thread](https://camunda.slack.com/archives/C013MEVQ4M9/p1724123798977289). This PR fix only one issue with the tests @mustafadagher

**Review by korthout — APPROVED** [review]
👍

**Comment by megglos** [comment]
@nicpuppa given this fixes the setup issue and the failure is an existing other issue, I would suggest to merge it to not have to include two different fixes into one PR. So once this is merged we can focus on the timer test fix separately, wdyt?

**Comment by nicpuppa** [comment]
> Can we skip the queue for that?

I think we can disable the queue from the settings, let me check

**Pull request merged**
