### PR TITLE
chore(project): prepare for next release

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

Bump the project version to `8.4.0-SNAPSHOT` after the `8.3.0` release.

**_Note_**: This was missed after the last release.

## Related issues

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually

Documentation:
* [ ] Javadoc has been written
* [ ] The documentation is updated

### CODE REVIEW

**Review by korthout — APPROVED** [review]
Thanks @tmetzke ❤️ 

👍 Changes look good to me

🔧 We should also update the zeebe version: https://github.com/camunda/zeebe-process-test/blob/4e8c8e17dffe7eb0f6f12daafbaaf0c8e0504c18/pom.xml#L92C32-L92C32

💭 Would be nice to add some automation for this or so

**Comment by tmetzke** [comment]
> Thanks @tmetzke ❤️
> 
> 👍 Changes look good to me
> 
> 🔧 We should also update the zeebe version: https://github.com/camunda/zeebe-process-test/blob/4e8c8e17dffe7eb0f6f12daafbaaf0c8e0504c18/pom.xml#L92C32-L92C32
> 
> 💭 Would be nice to add some automation for this or so

I'd bump the Zeebe version with https://github.com/camunda/zeebe-process-test/pull/978, if that is OK? It's a separate commit in that PR.

**Comment by tmetzke** [comment]
> I'd bump the Zeebe version with #978, if that is OK? It's a separate commit in that PR.

No, you're right, let's do this here in a second commit, makes more sense.

**Comment by tmetzke** [comment]
The bump to the latest Zeebe snapshot will probably fail the tests now. Are we fine with that for this PR, @korthout ?
This will be fixed with #978.

**Comment by tmetzke** [comment]
bors merge

**Comment by korthout** [comment]
@tmetzke Now the build fails because of the newly added value types. Seems that we either:
- have to do everything at once
- don't adjust the zeebe.version yet

**Comment by tmetzke** [comment]
My proposal: Let's adjust the Zeebe version over at #978 and not here.

**Comment by tmetzke** [comment]
bors merge

**Pull request merged**
