### PR TITLE
Update Zeebe dependency to 8.0.1

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR bumps the Zeebe dependency to 8.0.1.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually

Documentation:
* [ ] Javadoc has been written
* [ ] The documentation is updated

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@npepinpe Just a heads up that this PR should point to the `stable/8.0` branch instead of `main`. Not sure if this is clear enough in the release process.

**Comment by npepinpe** [comment]
Are the build and test on different OS's run in sequence and not in parallel? :thinking: It kind of looks like that's what happened

**Comment by remcowesterhoud** [comment]
Yes they are 😞 

It was changed here https://github.com/camunda/zeebe-process-test/pull/157
Running them in parallel caused a lot of flakiness which was presumably due to the speed of runners.

**Comment by npepinpe** [comment]
They don't run in different machines? I mean they need to run on different OS's, I always assumed they then ran on different machines :smile: Oh well, TIL

**Comment by remcowesterhoud** [comment]
I truly don't know. It could very well be that this was what's causing it is wrong. All I know is it did solve the issue 😅

**Pull request merged**
