### PR TITLE
feat: add updateJob rpc support

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

Add `updateJob` rpc support

## Related issues

related to https://github.com/camunda/zeebe-process-test/actions/runs/10295187776

### CODE REVIEW

**Review by megglos — APPROVED** [review]
❤️

**Review by tmetzke — APPROVED** [review]
👍 Looks good 🚀 
❓ Should we add a test case to `EngineClientTest` as well?

**Comment by nicpuppa** [comment]
> ❓ Should we add a test case to `EngineClientTest` as well?

Not yet, we don't have the command in the client  @tmetzke

**Comment by nicpuppa** [comment]
bors merge

**Comment by tmetzke** [comment]
> > ❓ Should we add a test case to `EngineClientTest` as well?
> 
> Not yet, we don't have the command in the client @tmetzke

That, eh, sounds plausible, yes 😅

**Comment by nicpuppa** [comment]
bors remove

**Comment by nicpuppa** [comment]
bors cancel

**Comment by nicpuppa** [comment]
We are going to remove the gRPC endpoint from Zeebe, so this PR is not needed anymore

**Pull request closed without merging**
